rm action_mailer & action_resource from dummy_app
No need to load this as we are not using. Also clears up this error
after updating to rails4 for the dummy_app:
/usr/local/var/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.0.3/lib/rails/railtie/configuration.rb:95:in
`method_missing': undefined method `action_mailer' for
<Rails::Application::Configuration:0x007f86abbe9d10> (NoMethodError)